driverClassName=com.mysql.cj.jdbc.Driver

##是否执行定时任务
#是否执行中间表的终端认证记录明细同步到一体化数据库表(0：执行，1：停止同步)
isSyncRadiusRadAuth=0
#是否执行用户入网表的认证成功同步到uap中(0：执行，1：停止同步)
isAccessSyncToUap=0
#是否每天0点清除一次终端认证记录明细的已读数据(0：执行，1：停止)
isRemoveRadiusRadAuth=0



#泰安的mysql配置
0504user=yth_sdn
0504password=taishan1532
0504connectUrl=jdbc:mysql://10.192.102.8:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true
ResultSet clientSql = statement.executeQuery(client);
#东营的mysql配置
0514user=yth_sdn
0514password=dongying1532
0514connectUrl=jdbc:mysql://10.158.192.45:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#聊城的mysql配置
0511user=yth_sdn
0511password=liaocheng1532
0511connectUrl=jdbc:mysql://10.141.177.51:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#日照的mysql配置
0516user=yth_sdn
0516password=rizhao1532
0516connectUrl=jdbc:mysql://10.141.161.70:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#青岛的mysql配置

0506user=yth_sdn
0506password=qingdao1532
0506connectUrl=jdbc:mysql://10.141.186.131:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#淄博的mysql配置
0502user=yth_sdn
0502password=zibo1532
0502connectUrl=jdbc:mysql://10.141.202.41:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#烟台的mysql配置
0507user=yth_sdn
0507password=yantai1507
0507connectUrl=jdbc:mysql://10.141.189.37:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#济南 mysql

3701user=idevelop_dev
3701password=Xtjc@2023
3701connectUrl=jdbc:mysql://rm-wk47jx45tm6cu5958.mysql.rds.ops-devcloud.sd.sgcc.com.cn:14306/idevelop?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8


#滨州 mysql
0509user=yth_sdn
0509password=binzhou1509
0509connectUrl=jdbc:mysql://10.141.183.141:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#莱芜 mysql
0517user=yth_sdn
0517password=laiwu1517
0517connectUrl=jdbc:mysql://10.141.153.74:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#临沂 mysql
0512user=yth_sdn
0512password=linyi_1512
0512connectUrl=jdbc:mysql://10.141.171.248:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#威海 mysql
0515user=yth_sdn
0515password=weihai_1515
0515connectUrl=jdbc:mysql://10.141.165.121:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#德州 mysql
0510user=yth_sdn
0510password=dezhou_1510
0510connectUrl=jdbc:mysql://10.140.118.203:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#菏泽 mysql
0513user=yth_sdn
0513password=heze_1513
0513connectUrl=jdbc:mysql://10.141.174.180:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true



#枣庄 mysql
0505user=yth_sdn
0505password=zaozhuang1505
0505connectUrl=jdbc:mysql://10.141.204.161:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#潍坊 mysql
0508user=yth_sdn
0508password=weifang_1508
0508connectUrl=jdbc:mysql://10.158.212.223:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true

#济宁 mysql
0503user=yth_sdn
0503password=jining1503
0503connectUrl=jdbc:mysql://10.141.195.247:3306/yth_sdn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=true


cityCodeArray=0504,0511,0514,0516,0506,0502,0507,0508,0501,0509,0517,0512,0515,0510,0513,0505,3701



# 信通一体化1.0 oracle数据库
sguap.driver-class-name=oracle.jdbc.driver.OracleDriver
sguap.url=jdbc:oracle:thin:@10.192.71.9:1521:orcl2
sguap.username=sguap
sguap.password=sguap





