CREATE TABLE `idevelop_warning` (
  `id` varchar(20) NOT NULL COMMENT 'id',
  `warning_number` varchar(50) DEFAULT NULL COMMENT '告警编码',
  `warning_source` varchar(255) DEFAULT NULL COMMENT '告警来源',
  `warning_device` varchar(100) DEFAULT NULL COMMENT '告警设备',
  `warning_level` varchar(10) DEFAULT NULL COMMENT '告警等级',
  `warning_type` varchar(50) DEFAULT NULL COMMENT '告警类型',
  `warning_reason` varchar(255) DEFAULT NULL COMMENT '告警原因',
  `warning_detail` varchar(255) DEFAULT NULL COMMENT '告警详情',
  `warning_gather_time` datetime DEFAULT NULL COMMENT '告警采集时间',
  `warning_begin_time` datetime DEFAULT NULL COMMENT '告警开始时间',
  `warning_end_time` datetime DEFAULT NULL COMMENT '告警结束时间',
  `warning_category` varchar(50) DEFAULT NULL COMMENT '告警设备分类id',
  `warning_category_name` varchar(50) DEFAULT NULL COMMENT '告警设备分类名称',
  `warning_device_type` varchar(50) DEFAULT NULL COMMENT '告警设备类型id',
  `warning_device_type_name` varchar(50) DEFAULT NULL COMMENT '告警设备类型名称',
  `warning_count` int(2) DEFAULT NULL COMMENT '告警次数',
  `warning_sort` tinyint(10) DEFAULT '0' COMMENT '告警排序',
  `warning_is_main` tinyint(1) DEFAULT '0' COMMENT '是否是主告警信息  0 是 1 否',
  `warning_show` tinyint(1) DEFAULT '0' COMMENT '存在子告警，列表显示 + 号 0 不显示 1 显示',
  `receive_unit` varchar(50) DEFAULT NULL COMMENT '领用单位id',
  `receive_unit_name` varchar(100) DEFAULT NULL COMMENT '领用单位名称',
  `receive_duty_dept` varchar(50) DEFAULT NULL COMMENT '领用部门',
  `receive_duty_dept_name` varchar(100) DEFAULT NULL COMMENT '领用部门名称',
  `receive_use_name` varchar(50) DEFAULT NULL COMMENT '领用责任人',
  `receive_use_phone` varchar(11) DEFAULT NULL COMMENT '领用责任人联系方式',
  `user_name` varchar(50) DEFAULT NULL COMMENT '使用人',
  `user_phone` varchar(11) DEFAULT NULL COMMENT '使用人联系方式',
  `confirm_status` tinyint(1) DEFAULT '0' COMMENT '告警确认状态 0 未确认 1 已确认 2 已忽略',
  `dispose_status` tinyint(1) DEFAULT '0' COMMENT '告警处置状态 0 未处置 1 已处置 2 已忽略',
  `dispose_user` varchar(20) DEFAULT NULL COMMENT '告警处置人',
  `dispose_phone` varchar(11) DEFAULT NULL COMMENT '告警处置人联系方式',
  `dispose_dept` varchar(50) DEFAULT NULL COMMENT '告警处置人所在部门',
  `dispose_time` datetime DEFAULT NULL COMMENT '告警处置时间',
  `dispose_result` varchar(255) DEFAULT NULL COMMENT '告警处置结果',
  `dispose_order` varchar(50) DEFAULT NULL COMMENT '告警处置关联工单编号',
  `dispose_order_type` tinyint(2) DEFAULT NULL COMMENT '告警处置关联工单类型 0 设备变更 1 设备投运',
  `dispose_device_code` varchar(50) DEFAULT NULL COMMENT '设备投运关联设备编码',
  `device_id` varchar(100) DEFAULT NULL COMMENT '台账设备id',
  `device_uuid` varchar(100) DEFAULT NULL COMMENT '台账设备UUID',
  `device_cid` varchar(100) DEFAULT NULL COMMENT '台账设备CID',
  `device_code` varchar(100) DEFAULT NULL COMMENT '台账设备编码',
  `device_ip` varchar(20) DEFAULT NULL COMMENT '台账设备ip',
  `device_mac` varchar(20) DEFAULT NULL COMMENT '台账设备mac',
  `device_factory_number` varchar(50) DEFAULT NULL COMMENT '台账设备出厂序列号',
  `device_factory_date` date DEFAULT NULL COMMENT '台账设备出厂日期',
  `device_hard_disk_size` double DEFAULT NULL COMMENT '硬盘容量（GB）',
  `device_memory_size` double DEFAULT NULL COMMENT '内存大小（GB）',
  `device_system_version` varchar(64) DEFAULT NULL COMMENT '操作系统版本号',
  `device_system_type` varchar(20) DEFAULT NULL COMMENT '操作系统类型',
  `device_last_time` datetime DEFAULT NULL COMMENT '设备最后一次活跃时间',
  `device_library_time` datetime DEFAULT NULL COMMENT '病毒库更新时间',
  `gather_ip` varchar(20) DEFAULT NULL COMMENT '采集台账设备ip',
  `gather_mac` varchar(20) DEFAULT NULL COMMENT '采集台账设备mac',
  `gather_factory_number` varchar(50) DEFAULT NULL COMMENT '采集台账设备出厂序列号',
  `gather_factory_date` date DEFAULT NULL COMMENT '采集台账设备出厂日期',
  `gather_hard_disk_size` double DEFAULT NULL COMMENT '采集硬盘容量（GB）',
  `gather_memory_size` double DEFAULT NULL COMMENT '采集内存大小（GB）',
  `gather_system_version` varchar(64) DEFAULT NULL COMMENT '采集操作系统版本号',
  `gather_system_type` varchar(20) DEFAULT NULL COMMENT '采集操作系统类型',
  `gather_last_time` datetime DEFAULT NULL COMMENT '采集最后一次活跃时间',
  `gather_library_time` datetime DEFAULT NULL COMMENT '采集病毒库更新时间',
  `history_time` varchar(255) DEFAULT NULL COMMENT '同一类型告警，不同时间组装，通过英文逗号隔开',
  `region_code` varchar(50) DEFAULT NULL COMMENT '设备所在区域编码',
  `create_user` varchar(50) DEFAULT NULL COMMENT '告警信息创建人',
  `create_time` datetime DEFAULT NULL COMMENT '告警信息创建时间',
  `update_user` varchar(50) DEFAULT NULL COMMENT '告警信息处理更新人',
  `update_time` datetime DEFAULT NULL COMMENT '告警信息操作更新时间',
  `status` tinyint(1) DEFAULT '0' COMMENT '无效字段（适配框架创建）',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '无效字段（适配框架创建）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备异动告警';
