package com.lnsoft.device.api.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2024-03-20T09:14:06.127+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFI_FM_XT_MAIN")
@XmlSeeAlso({ObjectFactory.class})
public interface ZfiFmXtMainInt {

    @WebMethod(operationName = "ZfiFmXtMain")
    @RequestWrapper(localName = "ZfiFmXtMain", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lnsoft.device.api.erp.ZfiFmXtMainType")
    @ResponseWrapper(localName = "ZfiFmXtMainResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lnsoft.device.api.erp.ZfiFmXtMainResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public String zfiFmXtMain(
        @WebParam(name = "Request", targetNamespace = "")
        String request
    );
}
