package com.lnsoft.device.api.erp;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2024-03-20T09:14:06.180+08:00
 * Generated source version: 3.2.7
 */

@WebServiceClient(name = "ZFI_FM_XT_MAIN",
	targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
	wsdlLocation = "http://10.158.252.24:8001/sap/bc/srt/wsdl/bndg_5B22826648141961E10000000A9EFC19/wsdl11/allinone/ws_policy/document?sap-client=800")
public class ZfiFmXtMainService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFI_FM_XT_MAIN");
	public final static QName ZFIFMXTMAIN = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFI_FM_XT_MAIN");

	static {
		URL url = null;
		try {
			// 设备建档
			// 设备报废
			// 正式环境
			url = new URL("http://10.158.252.24:8001/sap/bc/srt/wsdl/bndg_5B22826648141961E10000000A9EFC19/wsdl11/allinone/ws_policy/document?sap-client=800");

		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(ZfiFmXtMainService.class.getName())
				.log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}", "http://10.158.252.24:8001/sap/bc/srt/wsdl/bndg_5B22826648141961E10000000A9EFC19/wsdl11/allinone/ws_policy/document?sap-client=800");
		}
		WSDL_LOCATION = url;
	}

	public ZfiFmXtMainService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ZfiFmXtMainService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ZfiFmXtMainService() {
		super(WSDL_LOCATION, SERVICE);
	}

	public ZfiFmXtMainService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public ZfiFmXtMainService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public ZfiFmXtMainService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}


	/**
	 * @return returns ZFIFMXTMAIN
	 */
	@WebEndpoint(name = "ZFI_FM_XT_MAIN")
	public ZfiFmXtMainInt getZfiFmXtMain() {
		return super.getPort(ZFIFMXTMAIN, ZfiFmXtMainInt.class);
	}

	/**
	 * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns ZFIFMXTMAIN
	 */
	@WebEndpoint(name = "ZFI_FM_XT_MAIN")
	public ZfiFmXtMainInt getZfiFmXtMain(WebServiceFeature... features) {
		return super.getPort(ZFIFMXTMAIN, ZfiFmXtMainInt.class, features);
	}

}
