<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>idevelop-service</artifactId>
        <groupId>com.lnsoft</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>idevelop-device</artifactId>
    <name>${project.artifactId}</name>
    <version>${idevelop.project.version}</version>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-core-boot</artifactId>
            <version>${idevelop.tool.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15to18</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-core-swagger</artifactId>
            <version>${idevelop.tool.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15to18</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-device-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <!-- 轻骑兵工作流引擎 -->
        <dependency>
            <groupId>com.lnsoft.idevelop.hussar</groupId>
            <artifactId>idevelop-hussar-bpm-api</artifactId>
            <version>${idevelop.hussar.bpm.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15to18</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>2.5.6</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-cmdb-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-mongodb</artifactId>
            <version>3.4.18</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-dict-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-system-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-user-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-endpoint-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-data-api</artifactId>
            <version>${idevelop.project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>${easyexcel.version}</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft.sgcc</groupId>
            <artifactId>base</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft.sgcc</groupId>
            <artifactId>persistence</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft.sgcc</groupId>
            <artifactId>utils</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft.sgcc</groupId>
            <artifactId>exception</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.lnsoft.sgcc</groupId>
            <artifactId>rest</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>commons-pool</groupId>
            <artifactId>commons-pool</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lnsoft</groupId>
            <artifactId>idevelop-core-oss</artifactId>
            <version>${idevelop.tool.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jbarcode</groupId>
            <artifactId>jbarcode</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.zxing</groupId>
            <artifactId>zxing</artifactId>
            <version>3.2.1</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <!--suppress UnresolvedMavenProperty -->
                                <copy overwrite="true"
                                      tofile="${session.executionRootDirectory}/target/${artifactId}.jar"
                                      file="${project.build.directory}/${artifactId}.jar" />
                            </tasks>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
