#服务器配置
server:
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    # 线程配置
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 400

#spring配置
spring:
  cloud:
    sentinel:
      eager: true
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333

#feign配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false

#对外暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#knife4j配置
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: false
    username: idevelop
    password: idevelop
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://localhost
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh_cn
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright © 2023 Idevelop All Rights Reserved

#swagger配置信息
swagger:
  title: Idevelop 接口文档系统
  description: Idevelop 接口文档系统
  version: 1.0.0
  license: Powered By Idevelop
  licenseUrl: https://idevelopx.cn
  terms-of-service-url: https://idevelopx.cn
  contact:
    name: guozhao
    email: guozhao@163.com
    url: https://gitee.com/guo_z/idevelop-platform.git

#idevelop配置
idevelop:
  token:
    #使用 idevelop-auth服务 @com.lnsoft.test.SignKeyGenerator 获取
    sign-key: gYvd42zGQ8ggFmSA9KbeQP7tKr2ov3wa
    #使用 idevelop-auth服务 @com.lnsoft.test.AesKeyGenerator 获取
    aes-key: 3E6m32FjjxrOnDfBuazU7SUljDdQWheW
  xss:
    enabled: true
    skip-url:
      - /weixin
  secure:
    skip-url:
      - /test/**
    client:
      - client-id: sword
        path-patterns:
          - /sword/**
      - client-id: saber
        path-patterns:
          - /saber/**
  tenant:
    column: tenant_id
    tables:
      - idevelop_notice

