
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lnsoft.device.api.erp.deverp;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.5.10
 * 2025-01-20T18:48:21.461+08:00
 * Generated source version: 3.5.10
 *
 */

@WebService(
                      serviceName = "ZFI_FM_XT_MAIN",
                      portName = "ZFI_FM_XT_MAIN",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "http://27.41.18.4:18000/sap/bc/srt/wsdl/bndg_9DB7F665BC98A465E10000000A9EFC1C/wsdl11/allinone/ws_policy/document?sap-client=300",
                      endpointInterface = "com.lnsoft.device.api.erp.deverp.ZFIFMXTMAIN")

public class ZFI_FM_XT_MAINImpl implements ZFIFMXTMAIN {

    private static final Logger LOG = Logger.getLogger(ZFI_FM_XT_MAINImpl.class.getName());

    /* (non-Javadoc)
     * @see com.lnsoft.device.api.erp.deverp.ZFIFMXTMAIN#zfiFmXtMain(java.lang.String request)*
     */
    public String zfiFmXtMain(String request) {
        LOG.info("Executing operation zfiFmXtMain");

        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            throw new RuntimeException(ex);
        }
    }

}
