package com.lnsoft.device.api.erp.deverp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.10
 * 2025-01-20T18:48:21.510+08:00
 * Generated source version: 3.5.10
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFI_FM_XT_MAIN")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFIFMXTMAIN {

    @WebMethod(operationName = "ZfiFmXtMain")
    @RequestWrapper(localName = "ZfiFmXtMain", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lnsoft.device.api.erp.deverp.ZfiFmXtMain_Type")
    @ResponseWrapper(localName = "ZfiFmXtMainResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.lnsoft.device.api.erp.deverp.ZfiFmXtMainResponse")
    @WebResult(name = "Response", targetNamespace = "")
    public String zfiFmXtMain(

        @WebParam(name = "Request", targetNamespace = "")
        String request
    );
}
