package com.lnsoft.device.api.erp.deverp;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.10
 * 2025-01-20T18:48:21.564+08:00
 * Generated source version: 3.5.10
 *
 */
@WebServiceClient(name = "ZFI_FM_XT_MAIN",
                  wsdlLocation = "http://localhost:18000/sap/bc/srt/wsdl/bndg_9DB7F665BC98A465E10000000A9EFC1C/wsdl11/allinone/ws_policy/document?sap-client=300",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZFIFMXTMAIN_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFI_FM_XT_MAIN");
    public static final QName ZFIFMXTMAIN = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFI_FM_XT_MAIN");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:18000/sap/bc/srt/wsdl/bndg_9DB7F665BC98A465E10000000A9EFC1C/wsdl11/allinone/ws_policy/document?sap-client=300");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFIFMXTMAIN_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:18000/sap/bc/srt/wsdl/bndg_9DB7F665BC98A465E10000000A9EFC1C/wsdl11/allinone/ws_policy/document?sap-client=300");
        }
        WSDL_LOCATION = url;
    }

    public ZFIFMXTMAIN_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFIFMXTMAIN_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFIFMXTMAIN_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZFIFMXTMAIN_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZFIFMXTMAIN_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZFIFMXTMAIN_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZFIFMXTMAIN
     */
    @WebEndpoint(name = "ZFI_FM_XT_MAIN")
    public ZFIFMXTMAIN getZFIFMXTMAIN() {
        return super.getPort(ZFIFMXTMAIN, ZFIFMXTMAIN.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFIFMXTMAIN
     */
    @WebEndpoint(name = "ZFI_FM_XT_MAIN")
    public ZFIFMXTMAIN getZFIFMXTMAIN(WebServiceFeature... features) {
        return super.getPort(ZFIFMXTMAIN, ZFIFMXTMAIN.class, features);
    }

}
